import pandas as pd
df = pd.read_csv("train.csv")
print(df.head())
print(df.shape)
print(df.columns)
print("Shape of dataset:", df.shape)
print("Column names:")
print(df.columns)
print(df.dtypes)
print(df.isnull().sum())
df.info()